### ISSUE TITLE
.swp files uploaded to crates.io

### ISSUE THREAD

**Issue by Xion** [comex/rust-shlex#1]
Your crate seems to have been uploaded with (vim?) backup files, e.g. https://docs.rs/crate/shlex/0.1.1/source/ . You need to either add *.swp to .gitignore, or use package.exclude in Cargo.toml: http://doc.crates.io/manifest.html#the-exclude-and-include-fields-optional

**Comment by chih-hung** [comment]
Could someone publish a new version without those .swp files.
They have caused confusion when imported into other projects.
Thanks.

**Comment by fenhl** [comment]
Version 1.0.0 has been released and fixes this issue.
