### ISSUE TITLE
Support operating on bytes

### ISSUE THREAD

**Issue by epage** [comex/rust-shlex#12]
I'm experimenting with handling completions completely in `clap_complete`, like python's [argcomplete](https://github.com/kislyuk/argcomplete).  As an input, I'm getting `COMP_LINE` which is an environment variable containing the line being parsed, ie an `OsStr`.  I'm wanting to be able to handle non-unicode paths which means I can't operate on `OsStr::to_str` but need to convert to the raw bytes via `os_str_bytes`.  It looks like `shlex` operates on bytes internally but doesn't offer a constructor or outputs that stay within bytes.

If you are open to this, I'd be willing to implement support for it.

**Comment by fenhl** [comment]
This sounds like a reasonable addition.

**Comment by epage** [comment]
FYI I found I could implement completions in a different way which also saves a lot on complexity, so this is no longer a blocker for me.  Its unclear if this new strategy will work universally and I won't ever need this or if I might end up needing this eventually.
