### ISSUE TITLE
Windows path not suported?

### ISSUE THREAD

**Issue by mikoto2000** [comex/rust-shlex#20]
I implemented this code:
```rust
    let lex = Shlex::new(&args);
    let args = lex.collect::<Vec<_>>();
```

input is: `"-m F:\\llm\\C3TR-Adapter.f16.Q4_k_m.gguf --log-disable -ngl 43"`
output is: `["-m", "F:llmC3TR-Adapter.f16.Q4_k_m.gguf", "--log-disable", "-ngl", "43"]`

Windows path not suported?

**Comment by fenhl** [comment]
This crate provides POSIX-style shell escaping, so backslashes are used as escape characters. Quoting the path will work though:

`"-m 'F:\\llm\\C3TR-Adapter.f16.Q4_k_m.gguf' --log-disable -ngl 43"`
`["-m", "F:\\llm\\C3TR-Adapter.f16.Q4_k_m.gguf", "--log-disable", "-ngl", "43"]`

**Comment by mikoto2000** [comment]
@fenhl 
I see, thank you. I understand.

**Comment by stefnotch** [comment]
For future programmers that stumble upon this:

Shlex behaves the same way on all platforms. That's a feature and it makes shlex a lot more predictable.
If you are dealing with user input, and want to use the Windows behaviour, then I recommend using winsplit-rs together with a `#[cfg(target_os = "windows")]`
https://github.com/chipsenkbeil/winsplit-rs
