### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by fenhl** [comex/rust-shlex#7]
This crate has a few open issues/PRs and no apparent activity from the owner in over 5 years.

@comex Are you still around? If you don't have time to maintain this project anymore, I'd be willing to take over if you give me the necessary permissions here and on crates.io.

**Comment by comex** [comment]
Sorry for not responding.

Tell me how to give permissions and I'll do it.

**Comment by fenhl** [comment]
For GitHub, go to <https://github.com/comex/rust-shlex/settings/access>, click on “Invite a collaborator”.

For crates.io, run `cargo owner --add fenhl shlex`.

**Comment by comex** [comment]
Done.  Sorry for sitting on this for such a long time...

**Comment by fenhl** [comment]
Thank you. I'll start reviewing issues and PRs in a minute.
